// V1 source definitions for seeding the database
export const V1_SOURCES = [
  {
    name: "Naavik",
    url: "https://naavik.co",
    feed_url: "https://naavik.co/feed",
    source_type: "newsletter",
  },
  {
    name: "Deconstructor of Fun",
    url: "https://www.deconstructoroffun.com",
    feed_url: "https://www.deconstructoroffun.com/blog?format=rss",
    source_type: "newsletter",
  },
  {
    name: "GameDiscoverCo",
    url: "https://gamediscover.co",
    feed_url: "https://newsletter.gamediscover.co/feed",
    source_type: "newsletter",
  },
  {
    name: "MobileGamer.biz",
    url: "https://mobilegamer.biz",
    feed_url: "https://mobilegamer.biz/feed/",
    source_type: "news",
  },
  {
    name: "GamesIndustry.biz",
    url: "https://www.gamesindustry.biz",
    feed_url: "https://www.gamesindustry.biz/feed",
    source_type: "news",
  },
  {
    name: "Game File",
    url: "https://www.gamefile.news",
    feed_url: "https://www.gamefile.news/feed",
    source_type: "newsletter",
  },
  {
    name: "InvestGame",
    url: "https://investgame.net",
    feed_url: "https://investgame.net/feed",
    source_type: "analysis",
  },
  {
    name: "Elite Game Developers",
    url: "https://elitegamedevelopers.substack.com",
    feed_url: "https://elitegamedevelopers.substack.com/feed",
    source_type: "newsletter",
  },
  {
    name: "SuperJoost Playlist",
    url: "https://superjoost.substack.com",
    feed_url: "https://superjoost.substack.com/feed",
    source_type: "newsletter",
  },
  {
    name: "Game Developer",
    url: "https://www.gamedeveloper.com",
    feed_url: "https://www.gamedeveloper.com/rss.xml",
    source_type: "news",
  },
  {
    name: "Hit Points",
    url: "https://hitpoints.substack.com",
    feed_url: "https://hitpoints.substack.com/feed",
    source_type: "newsletter",
  },
  {
    name: "GameMakers",
    url: "https://gamemakers.substack.com",
    feed_url: "https://gamemakers.substack.com/feed",
    source_type: "analysis",
  },
  {
    name: "PocketGamer.biz",
    url: "https://www.pocketgamer.biz",
    feed_url: "https://www.pocketgamer.biz/rss/",
    source_type: "news",
  },
  {
    name: "Video Games Chronicle",
    url: "https://www.videogameschronicle.com",
    feed_url: "https://www.videogameschronicle.com/feed",
    source_type: "news",
  },
  {
    name: "GameRefinery",
    url: "https://www.gamerefinery.com",
    feed_url: "https://www.gamerefinery.com/blog/feed/",
    source_type: "analysis",
  },
  {
    name: "80 Level",
    url: "https://80.lv",
    feed_url: "https://80.lv/feed",
    source_type: "news",
  },
  {
    name: "Eurogamer",
    url: "https://www.eurogamer.net",
    feed_url: "https://www.eurogamer.net/feed",
    source_type: "news",
  },
] as const;
