// V1 source definitions for seeding the database
export const V1_SOURCES = [
  {
    name: "Naavik",
    url: "https://naavik.co",
    feed_url: "https://naavik.co/feed",
    source_type: "newsletter",
  },
  {
    name: "Deconstructor of Fun",
    url: "https://www.deconstructoroffun.com",
    feed_url: "https://www.deconstructoroffun.com/blog?format=rss",
    source_type: "newsletter",
  },
  {
    name: "GameDiscoverCo",
    url: "https://gamediscover.co",
    feed_url: "https://newsletter.gamediscover.co/feed",
    source_type: "newsletter",
  },
  {
    name: "MobileGamer.biz",
    url: "https://mobilegamer.biz",
    feed_url: "https://mobilegamer.biz/feed/",
    source_type: "news",
  },
  {
    name: "GamesIndustry.biz",
    url: "https://www.gamesindustry.biz",
    feed_url: "https://www.gamesindustry.biz/feed",
    source_type: "news",
  },
  {
    name: "Game File",
    url: "https://www.gamefile.news",
    feed_url: "https://www.gamefile.news/feed",
    source_type: "newsletter",
  },
  {
    name: "InvestGame",
    url: "https://investgame.net",
    feed_url: "https://investgame.net/feed",
    source_type: "analysis",
  },
  {
    name: "Elite Game Developers",
    url: "https://elitegamedevelopers.substack.com",
    feed_url: "https://elitegamedevelopers.substack.com/feed",
    source_type: "newsletter",
  },
  {
    name: "SuperJoost Playlist",
    url: "https://superjoost.substack.com",
    feed_url: "https://superjoost.substack.com/feed",
    source_type: "newsletter",
  },
  {
    name: "Game Developer",
    url: "https://www.gamedeveloper.com",
    feed_url: "https://www.gamedeveloper.com/rss.xml",
    source_type: "news",
  },
  {
    name: "Hit Points",
    url: "https://hitpoints.substack.com",
    feed_url: "https://hitpoints.substack.com/feed",
    source_type: "newsletter",
  },
  {
    name: "GameMakers",
    url: "https://gamemakers.substack.com",
    feed_url: "https://gamemakers.substack.com/feed",
    source_type: "analysis",
  },
  {
    name: "PocketGamer.biz",
    url: "https://www.pocketgamer.biz",
    feed_url: "https://www.pocketgamer.biz/rss/",
    source_type: "news",
  },
  {
    name: "Video Games Chronicle",
    url: "https://www.videogameschronicle.com",
    feed_url: "https://www.videogameschronicle.com/feed",
    source_type: "news",
  },
  {
    name: "GameRefinery",
    url: "https://www.gamerefinery.com",
    feed_url: "https://www.gamerefinery.com/blog/feed/",
    source_type: "analysis",
  },
  {
    name: "80 Level",
    url: "https://80.lv",
    feed_url: "https://80.lv/feed",
    source_type: "news",
  },
  {
    name: "Eurogamer",
    url: "https://www.eurogamer.net",
    feed_url: "https://www.eurogamer.net/feed",
    source_type: "news",
  },
  {
    name: "David Kaye",
    url: "https://blog.davidkaye.co",
    feed_url: "https://blog.davidkaye.co/feed",
    source_type: "newsletter",
  },
  {
    name: "Metaversus (Ryan Foo)",
    url: "https://metaversus.substack.com",
    feed_url: "https://metaversus.substack.com/feed",
    source_type: "newsletter",
  },
  {
    name: "The Game Business",
    url: "https://thegamebusiness.substack.com",
    feed_url: "https://thegamebusiness.substack.com/feed",
    source_type: "newsletter",
  },
  {
    name: "CORE: About Them Video Games",
    url: "https://www.core.show",
    feed_url: "https://coreshow.substack.com/feed",
    source_type: "newsletter",
  },
  {
    name: "Mobile Gaming Today",
    url: "https://gamigion.substack.com",
    feed_url: "https://gamigion.substack.com/feed",
    source_type: "newsletter",
  },
  {
    name: "Video Games Industry Memo",
    url: "https://videogamesindustrymemo.substack.com",
    feed_url: "https://videogamesindustrymemo.substack.com/feed",
    source_type: "newsletter",
  },
  {
    name: "NextBigGames",
    url: "https://vamsinextbiggames.substack.com",
    feed_url: "https://vamsinextbiggames.substack.com/feed",
    source_type: "newsletter",
  },
  {
    name: "GameDev Reports",
    url: "https://gamedevreports.substack.com",
    feed_url: "https://gamedevreports.substack.com/feed",
    source_type: "newsletter",
  },
  {
    name: "The Gamer Educator",
    url: "https://thegamereducator.substack.com",
    feed_url: "https://thegamereducator.substack.com/feed",
    source_type: "newsletter",
  },
  {
    name: "Think Like A Game Designer",
    url: "https://justingarydesign.substack.com",
    feed_url: "https://justingarydesign.substack.com/feed",
    source_type: "newsletter",
  },
  {
    name: "Ludological Alchemy",
    url: "https://ludologicalalchemy.substack.com",
    feed_url: "https://ludologicalalchemy.substack.com/feed",
    source_type: "newsletter",
  },
  {
    name: "MurkMail",
    url: "https://murkdice.substack.com",
    feed_url: "https://murkdice.substack.com/feed",
    source_type: "newsletter",
  },
  {
    name: "Updater",
    url: "https://shannonliao.substack.com",
    feed_url: "https://shannonliao.substack.com/feed",
    source_type: "newsletter",
  },
] as const;
